version: '3.10'

services:
    web:
      build: ./Ssite
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./Ssite/:/opt/3pich/Ssite/
      ports:
        - 8000
      env_file:
        - ./.env.dev
    nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - web

